version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: jlauinger/docman
    ports:
      - 8080:80
    links:
      - mysql
    environment:
      DB_HOST: mysql
      DB_DATABASE: docman
      DB_USERNAME: docman
      DB_PASSWORD: password
      APP_KEY: xlhF31NeOlibJcoOW9tvZg7TkHcAZI3a
    volumes:
      - ./data/documents:/srv/app/storage/app/documents
      - ./data/import:/docmanimport
      - ./data/docman.htpasswd:/srv/app/.htpasswd

  mysql:
    image: mariadb
    environment:
      MYSQL_DATABASE: docman
      MYSQL_USER: docman
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
